//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nfro.App.Android.AppServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AppServiceSoap", Namespace="http:/localhost/NfroServer/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Result))]
    public partial class AppService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public AppService() {
            this.Url = "http://localhost/NfroServer/AppService.asmx";
        }
        
        public AppService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http:/localhost/NfroServer/GetAppInfos", RequestNamespace="http:/localhost/NfroServer/", ResponseNamespace="http:/localhost/NfroServer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AppInfo[] GetAppInfos() {
            object[] results = this.Invoke("GetAppInfos", new object[0]);
            return ((AppInfo[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAppInfos(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAppInfos", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public AppInfo[] EndGetAppInfos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AppInfo[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http:/localhost/NfroServer/CreateUserApp", RequestNamespace="http:/localhost/NfroServer/", ResponseNamespace="http:/localhost/NfroServer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ObjectValueResult CreateUserApp(Token token, AppType appType) {
            object[] results = this.Invoke("CreateUserApp", new object[] {
                        token,
                        appType});
            return ((ObjectValueResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateUserApp(Token token, AppType appType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateUserApp", new object[] {
                        token,
                        appType}, callback, asyncState);
        }
        
        /// <remarks/>
        public ObjectValueResult EndCreateUserApp(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ObjectValueResult)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/localhost/NfroServer/")]
    public partial class AppInfo {
        
        /// <remarks/>
        public AppType AppType;
        
        /// <remarks/>
        public string AppName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/localhost/NfroServer/")]
    public enum AppType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        GooglePlus,
        
        /// <remarks/>
        Twitter,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectValueResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/localhost/NfroServer/")]
    public partial class Result {
        
        /// <remarks/>
        public bool Success;
        
        /// <remarks/>
        public string[] Errors;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/localhost/NfroServer/")]
    public partial class ObjectValueResult : Result {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/localhost/NfroServer/")]
    public partial class Token {
        
        /// <remarks/>
        public string TokenString;
        
        /// <remarks/>
        public System.DateTime DateExpires;
        
        /// <remarks/>
        public Device DeviceType;
        
        /// <remarks/>
        public long UserId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/localhost/NfroServer/")]
    public enum Device {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Desktop,
        
        /// <remarks/>
        iPhone,
        
        /// <remarks/>
        Android,
        
        /// <remarks/>
        Windows,
    }
}
